// data/projects.js
export const projects = [
    {
        id: 1,
        title: 'Rosie Paws- Pet Care Platform',
        slug: 'rosie-paws-pet-care-platform',
        description: 'Modern Online Platform for pet care with advance features',
        fullDescription: 'Rosie Paws is a comprehensive pet care platform that connects pet owners with professional caregivers, veterinarians, and pet services. The platform features real-time booking, pet health tracking, medication reminders, and a community forum for pet owners.',
        category: 'Web Development',
        image: '/images/cardImage1.png',
        images: ['/images/cardImage1.png', '/images/cardImage1.png', '/images/cardImage1.png'],
        tags: ['React', 'UI/UX', 'Node.js'],
        status: 'Web Development',
        devices: ['desktop'],
        client: 'Rosie Paws Inc.',
        duration: '3 months',
        year: '2024',
        liveUrl: 'https://rosiepaws.com',
        githubUrl: 'https://github.com/username/rosie-paws',
        features: [
            'Real-time pet care booking system',
            'Pet health tracking dashboard',
            'Medication reminder system',
            'Community forum for pet owners',
            'Integrated payment gateway',
            'Mobile-responsive design'
        ],
        technologies: ['React.js', 'Node.js', 'MongoDB', 'Socket.io', 'Stripe API', 'Tailwind CSS']
    },
    {
        id: 2,
        title: 'Finder- Social Media Dating App',
        slug: 'finder-social-media-dating-app',
        description: 'Modern Online social media dating platform with Advanced features',
        fullDescription: 'Finder is a next-generation dating app that combines social media features with intelligent matching algorithms. Users can create rich profiles, share stories, and connect through various interactive features including video calls and virtual dates.',
        category: 'app',
        image: '/images/cardImage2.png',
        images: ['/images/cardImage2.png', '/images/cardImage2.png', '/images/cardImage2.png'],
        tags: ['Flutter', 'UI/UX', 'Mobile'],
        status: 'Mobile App',
        devices: ['mobile'],
        client: 'Finder Technologies',
        duration: '4 months',
        year: '2024',
        liveUrl: 'https://play.google.com/store/apps/details?id=com.finder',
        features: [
            'AI-powered matching algorithm',
            'Video calling integration',
            'Story sharing feature',
            'Location-based matching',
            'Advanced privacy controls',
            'In-app messaging system'
        ],
        technologies: ['Flutter', 'Dart', 'Firebase', 'WebRTC', 'Google Maps API', 'Machine Learning']
    },
    {
        id: 3,
        title: 'Paria- Beauty Parlour App',
        slug: 'paria-beauty-parlour-app',
        description: 'Complete online appointment for parlour with real-time features',
        fullDescription: 'Paria is a comprehensive beauty parlour management app that streamlines appointment booking, service management, and customer relationship management. It features real-time availability, service customization, and integrated payment processing.',
        category: 'app',
        image: '/images/cardImage3.png',
        images: ['/images/cardImage3.png', '/images/cardImage3.png', '/images/cardImage3.png'],
        tags: ['Flutter', 'UI/UX', 'Node.js'],
        status: 'Mobile App',
        devices: ['mobile', 'desktop'],
        client: 'Paria Beauty Salons',
        duration: '2.5 months',
        year: '2024',
        features: [
            'Real-time appointment booking',
            'Service catalog management',
            'Staff scheduling system',
            'Customer loyalty program',
            'Inventory management',
            'Analytics dashboard'
        ],
        technologies: ['Flutter', 'Node.js', 'PostgreSQL', 'Redis', 'Push Notifications', 'Payment Gateway']
    },
    {
        id: 4,
        title: 'Sarqeen- Shipment Delivery App',
        slug: 'sarqeen-shipment-delivery-app',
        description: 'Secure and user-friendly delivery shipment app',
        fullDescription: 'Sarqeen is a robust shipment delivery application that provides end-to-end package tracking, secure delivery management, and real-time communication between senders, recipients, and delivery personnel.',
        category: 'app',
        image: '/images/cardImage4.png',
        images: ['/images/cardImage4.png', '/images/cardImage4.png', '/images/cardImage4.png'],
        tags: ['Flutter', 'UI/UX', 'Node.js'],
        status: 'Mobile App',
        devices: ['mobile'],
        client: 'Sarqeen Logistics',
        duration: '3.5 months',
        year: '2023',
        features: [
            'Real-time package tracking',
            'Secure delivery verification',
            'Route optimization',
            'Digital signature capture',
            'Multi-language support',
            'Offline functionality'
        ],
        technologies: ['Flutter', 'Node.js', 'MongoDB', 'Google Maps API', 'FCM', 'QR Code Scanner']
    },
    {
        id: 5,
        title: 'Gama Cabana App',
        slug: 'gama-cabana-app',
        description: 'Modern Online Platform for sport with advanced features',
        fullDescription: 'Gama Cabana is a comprehensive sports platform that connects athletes, coaches, and sports enthusiasts. The app features training programs, performance tracking, community features, and sports event management.',
        category: 'app',
        image: '/images/cardImage5.png',
        images: ['/images/cardImage5.png', '/images/cardImage5.png', '/images/cardImage5.png'],
        tags: ['Flutter', 'UI/UX', 'Mobile'],
        status: 'Mobile App',
        devices: ['mobile'],
        client: 'Gama Sports Club',
        duration: '4 months',
        year: '2023',
        features: [
            'Training program management',
            'Performance analytics',
            'Social networking for athletes',
            'Event booking system',
            'Video coaching sessions',
            'Fitness tracking integration'
        ],
        technologies: ['Flutter', 'Firebase', 'Machine Learning', 'Video Streaming', 'Health Kit', 'Social APIs']
    },
    {
        id: 6,
        title: 'Car Genie- Car Booking App',
        slug: 'car-genie-car-booking-app',
        description: 'Modern Online car booking with advanced features',
        fullDescription: 'Car Genie is an innovative car rental platform that simplifies vehicle booking, provides flexible rental options, and ensures seamless user experience from booking to return. The app includes features like keyless entry and smart vehicle management.',
        category: 'app',
        image: '/images/cardImage6.png',
        images: ['/images/cardImage6.png', '/images/cardImage6.png', '/images/cardImage6.png'],
        tags: ['Flutter', 'UI/UX', 'Node.js'],
        status: 'Mobile App',
        devices: ['mobile'],
        client: 'Car Genie Rentals',
        duration: '3 months',
        year: '2023',
        features: [
            'Smart car booking system',
            'Keyless entry integration',
            'Real-time vehicle tracking',
            'Damage assessment tool',
            'Flexible pricing models',
            'Customer support chat'
        ],
        technologies: ['Flutter', 'Node.js', 'IoT Integration', 'GPS Tracking', 'Payment Gateway', 'ML Vision API']
    }
];